---
version: 0.2
phases:

  install:
    commands:
      - |
        docker --version
        git --version
        aws --version
        kubectl version --client --short
      - |
        aws secretsmanager get-secret-value --secret-id github/dev-key --output text --query SecretString > k
        chmod 600 k 
        eval "$(ssh-agent -s)"
        ssh-add k
        rm k
      - | 
        git clone git@github.com:$REPOSITORY_USERNAME/eksworkshop-cicd-pipeline-imagebuilder.git
        cd eksworkshop-cicd-pipeline-imagebuilder
        ls      

  pre_build:
    commands:
      - TAG="$REPOSITORY_NAME-$REPOSITORY_BRANCH--$(date +%Y-%m-%d-%H-%M-%S)--$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - |
        cd $CODEBUILD_SRC_DIR/webapp
        ./generate-dockerfile.sh
        cat Dockerfile

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/webapp
      - |
        docker build --tag $REPOSITORY_URI:$TAG .
        docker push $REPOSITORY_URI:$TAG
      - |
        cd $CODEBUILD_SRC_DIR
        echo "$REPOSITORY_URI:$TAG" > ecr-image-tag.txt
        cat ecr-image-tag.txt
      
artifacts:
  files:
    - '**/*'