---
version: 0.2

env:
  shell: bash
  
phases:

  pre_build:
    commands:
      - sed --version
      - bash --version
      - source || echo no worries
      - TAG="$REPOSITORY_NAME-$REPOSITORY_BRANCH--$(date +%Y-%m-%d-%H-%M-%S)--$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - |
        cd $CODEBUILD_SRC_DIR/webapp
        ./generate-dockerfile.sh
        cat Dockerfile

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/webapp
      - |
        docker build --tag $REPOSITORY_URI:$TAG .
        docker push $REPOSITORY_URI:$TAG
      - |
        cd $CODEBUILD_SRC_DIR
        echo "$REPOSITORY_URI:$TAG" > ecr-image-tag.txt
        cat ecr-image-tag.txt
      
artifacts:
  files:
    - '**/*'